djangoprj/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import logout
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^', include('apps.home.urls')),
    # url(r'^account/', include('apps.account.urls')),
    # url(r'^search', include('apps.query.urls')),
    url(r'^$', 'myapp.views.index', name='index'),
    url(r'^login$', 'myapp.views.login', name='login'),
    url(r'^register$', 'myapp.views.register', name='register'),
    url(r'^logout$', logout, kwargs={'next_page':'/'}, name="logout"),
    url(r'^search', 'myapp.views.search', name='search'),
    url(r'^tickets', 'myapp.views.tickets', name='tickets'),
    url(r'^price', 'myapp.views.price', name='price'),
    # url(r'^admin/', include(admin.site.urls)),
)

myapp/models.py
from django.db import models

# Create your models here.
class Event(models.Model):
  id = models.IntegerField(primary_key=True)
  title = models.CharField(max_length=200,null=True)
  venue = models.CharField(max_length=100,null=True)
  primaryPerformer = models.CharField(max_length=200,null=True)
  secondaryPerformer = models.CharField(max_length=200,null=True)
  grouping = models.CharField(max_length=100,null=True)

class Listing(models.Model):
  id = models.IntegerField(primary_key=True)
  event = models.ForeignKey(Event)
  quantity = models.IntegerField()
  zoneId = models.IntegerField(null=True)
  zoneName = models.CharField(max_length=200,null=True)
  sectionId = models.IntegerField(null=True)
  sectionName = models.CharField(max_length=200,null=True)
  row = models.CharField(max_length=200)
  seatNumbers = models.CharField(max_length=200)
  currentPrice = models.FloatField(null=True)

class SoldTicket(models.Model):
  listingId = models.IntegerField()
  event = models.ForeignKey(Event)
  zoneId = models.IntegerField(null=True)
  zoneName = models.CharField(max_length=200,null=True)
  sectionId = models.IntegerField(null=True)
  sectionName = models.CharField(max_length=200,null=True)
  row = models.CharField(max_length=200)
  seatNumber = models.CharField(max_length=200,null=True)
  currentPrice = models.FloatField(null=True)

myapp/views.py
from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth.decorators import login_required
# from apps.account.forms import LoginForm, RegisterForm
from  django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.http import Http404 
import logging
import json
import time
import stubhub

# Create your views here.
def login(request):
  if request.user.is_authenticated():
    return redirect('index')
  else:
    if request.method == 'POST':
      form = AuthenticationForm(data=request.POST)
      if form.is_valid():
        auth_login(request, form.get_user())
        logging.info('login!')
        return redirect('index')
      else:
        logging.info("invalid form")
    else:
      logging.info('not post')
      form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})

def register(request):
  if request.user.is_authenticated():
    return redirect('index')
  else:
    if request.method == 'POST':
      form = UserCreationForm(data=request.POST)
      if form.is_valid():
        user = form.save()
        user.backend = settings.AUTHENTICATION_BACKENDS[0]
        auth_login(request, user)
        return redirect('index')
      else:
        logging.info('invalid form')
        
    else:
      form = UserCreationForm()
    return render(request, 'register.html', {'form': form})

def index(request):
  if request.user.is_authenticated():
    # queryForm = QueryForm()
    return render(request, 'index.html')
  else:
    login_form = AuthenticationForm()
    register_form = UserCreationForm()
    return render(request, 'index.html', {'login_form': login_form, 'register_form': register_form})

@login_required
def search(request):
  query = request.GET
  if not query:
    return render(request, 'search.html')
  else:
    logging.info(query)
    result = stubhub.getEvents(query)
    logging.info(result)
    return render(request, 'search.html', {'result': result})

def tickets(request):
  eventId = request.GET.get('eventId')
  if not eventId:
    return render(request, 'tickets.html', {'error': '404 not found'})
  else:
    result = stubhub.getTickets(eventId)
    # logging.info(result)
    return render(request, 'tickets.html', {'eventId': eventId, 'result': result})

def price(request):
  query = request.GET
  logging.info(query)
  # query.eventId
  # query.sectionName
  # query.row
  # query.seatNumbers
  # time.sleep(1)
  return HttpResponse(json.dumps({'price': 100.00}), content_type="application/json")

myapp/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    {% block head %}
      <title>Myapp</title>
    {% endblock %}
    
    {% block stylesheet %}
      <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
      <link rel="stylesheet" type="text/css" href="/static/css/base.css">
    {% endblock %}
    
    {% block javascript %}
      <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
      <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    {% endblock %}
  </head>
  <body>
    {% block navigation %}
      <header class="navbar">
        <div class="container">
          <div class="navbar-header">
            <a href="/" class="navbar-brand brand">Myapp</a>
          </div>
          <div class="navbar-right user-info">
            {% if user.is_authenticated %}
              <a href="">Welcome, {{ user.username }}.</a>
              <a href="{% url 'logout' %}"> Logout</a>            
            {% else %}
              <a href="{% url 'login' %}"> Login</a>
              <a href="{% url 'register' %}"> Sign up</a>
            {% endif %}
        </div>
        <!-- {% if user.is_authenticated %}
          <a>Welcome, {{ user.username }}. Thanks for logging in.</a>
          <a href="{% url 'logout' %}"> Logout</a>
        {% else %}
          <form action="{% url 'login' %}" method="post">
            {% csrf_token %}
            {{ login_form.as_p }}
            <input type="submit" value="Login">
          </form>
          <form action="{% url 'register' %}" method="post">
            {% csrf_token %}
            {{ register_form.as_p }}
            <input type="submit" value="Sign up">
          </form>
        {% endif %} -->
      </header>

    {% endblock %}

    <div class="container">
      {% block body %}
      {% endblock %}
    </div>

    </body>
</html>

myapp/templates/index.html
{% extends "base.html" %}

{% block stylesheet %}
  {{ block.super }}
  <link rel="stylesheet" href="/static/css/index.css">
{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-md-3 search-bar">
      {% block search %}
      <div class="search-title">
        <p>Search for tickets:</p>
      </div>
      <div class="search-form-wrap">
          <form id="search-form" action="{% url 'search' %}" method="get">
            <div>
              <p>
                <label for="id_grouping"> Grouping: </label>
              </p>
              <input type="text" name="groupingName" id="id_grouping" value="NFL">
            </div>
            <div>
              <p>
                <label for="id_city"> City: </label>
              </p>
              <input type="text" name="city" id="id_city" value="East Rutherford">
            </div>
            <div>
              <p>
                <label for="id_team"> Team: </label>
              </p>
              <input type="text" name="performerName" id="id_team" value="Giants">
            </div>
            <div>
              <p>
                <label for="id_venue"> Venue: </label>
              </p>
              <input type="text" name="venue" id="id_venue" value="Metlife Stadium">
            </div>
            <div>
              <p>
                <label for="id_date"> Date: </label>
              </p>
              <input type="text" name="date" id="id_date" value="2014-12-15">
            </div>
          <button type="submit" class="btn btn-default" id="search-button">Search</button>
        </form>
      </div>
      {% endblock %}
    </div>
    <div class="col-md-9 content">
      {% block content %}
        <p> Some stuff shown in home page </p>
      {% endblock %}
    </div>
  </div>
{% endblock %}

myapp/templates/login.html
<p>This is login page</p>
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Login">
  <p>or <a href="{% url 'register' %}">sign up</a></p>
</form>

myapp/templates/register.html
<p>This is sign up page</p>
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Sign up">
</form>
<p><a href="{% url 'login' %}">already has an account?</a></p>

myapp/templates/search.html
{% extends "index.html" %}

{% block stylesheet %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="/static/css/search.css">
{% endblock %}

{% block content %}
  <p>Result</p>
  {% if result %}
    {% if result.error %}
      <p>{{ result.error }}</p>
    {% elif result.eventlist %}
      <div class="results">
        {% for id, title in result.eventlist.items %}
          <div>
            {% with id|stringformat:"s" as str_id %}
              <a class="event-title" href={{ "/tickets?eventId="|add:str_id }}>{{ title }}</a>
            {% endwith %}
          </div>
        {% endfor %}
      </div>
    {% endif %}
  {% endif %}

  
</div>
{% endblock %}

myapp/templates/tickets.html
{% extends "base.html" %}

{% block stylesheet %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/plug-ins/9dcbecd42ad/integration/bootstrap/3/dataTables.bootstrap.css">
  <link rel="stylesheet" href="/static/css/ticket.css">
{% endblock %}

{% block javascript %}
  {{ block.super }}
  <script type="text/javascript" language="javascript" src="//cdn.datatables.net/1.10.4/js/jquery.dataTables.min.js"></script>
  <script type="text/javascript" src="//cdn.datatables.net/plug-ins/9dcbecd42ad/integration/bootstrap/3/dataTables.bootstrap.js"></script>
  <script type="text/javascript" src="/static/js/tickets.js"></script>
{% endblock %}

{% block body %}
{% if error %}
  <p>{{ error }}</p>
{% endif %}
{% if result %}
<div class="row">
  <div class="col-md-10">
    <div id="ticket-table-wrap">
      <table id="ticket-table" class="table table-condensed table-hover">
        <caption>Active Listings:</caption>
        <thead>
          <tr>
            <th>zoneName</th>
            <th>sectionName</th>
            <th>row</th>
            <th>seatNumbers</th>
            <th>quantity</th>
            <th>currentPrice</th>
          </tr>
        </thead>
        <tbody>
          {% for ticket in result %}
            <tr>
              <td>{{ ticket.zoneName }}</td>
              <td>{{ ticket.sectionName }}</td>
              <td>{{ ticket.row }}</td>
              <td>{{ ticket.seatNumbers }}</td>
              <td>{{ ticket.quantity }}</td>
              <td>{{ ticket.currentPrice.amount }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  <div class="col-md-2" id="price-bar">
    <div id="price-title">
      <p> Price Estimation: </p>
    </div>
    <div id="price-form-wrap">
        <form id="price-form" action="{% url 'price' %}" method="get">
          <input type="hidden" name="eventId" value={{ eventId }}>
          <div>
            <p>
              <label for="id_sectionName"> Section: </label>
            </p>
            <input type="text" name="sectionName" id="id_sectionName">
          </div>
          <div>
            <p>
              <label for="id_row"> Row: </label>
            </p>
            <input type="text" name="row" id="id_row">
          </div>
          <div>
            <p>
              <label for="id_seatNumbers"> Seats: </label>
            </p>
            <input type="text" name="seatNumbers" id="id_seatNumbers">
          </div>
          <div>
            <p>
              <label for="id_facevalue"> Facevalue: </label>
            </p>
            <input type="text" name="facevalue" id="id_facevalue">
          </div>
        <button type="submit" class="btn btn-default" id="price-button">Calculate</button>
      </form>
    </div>
    <div id="price-result">
      <p> Estimated Price: </p>
      <p align="right"><span id="estimated-price"> 10 </span> $</p>
    </div>
  </div>
</div>
{% endif %}
{% endblock %}